added initial project
FHOOEAIST/Itamae pull request #1
Opened 2020-10-22 11:53 UTC by oliver-krauss

Publication of initial project

2020-10-22 12:04 UTC, pointan approved these changes

2020-11-16 08:07 UTC, aschuler84 requested changes
Some minor changes. However, I skipped the Lexer/Parser files.

2020-11-16 08:07 UTC, aschuler84 commented on README.md
> +The editor will be automatically starting, if the language fsh is identified
will be started automatically

2020-11-16 08:07 UTC, aschuler84 commented on README.md
> +Different colorization for declaration keywords, additional keyword, comments, and todos.
coloring?

2020-11-16 08:07 UTC, aschuler84 commented on extension.js
> +}
Remove vs-code template commands

2020-11-16 08:07 UTC, aschuler84 commented on language_server/providers/completion.js
> +}
make return value of method an attribute. Currently, the Array structure is created new in every call. Is this intentionally?

2020-11-16 08:07 UTC, aschuler84 commented on language_server/providers/completion.js
> +        item.detail = "Id details";
elseif and if check for the same value

2020-11-16 08:07 UTC, aschuler84 commented on language_server/providers/completion.js
> +    else if (item.data === 2) {
provide an enum/constants for the values being checked

2020-11-16 08:07 UTC, aschuler84 commented on package.json
> +	"description": "An interactiv editor for designing and writing FHIR-Shorthand specifications",
why is there a difference - fsh-editor vs. fsh_editor

2020-11-16 08:07 UTC, aschuler84 commented on src/extension.js
> +//this definisions are for the language server
definitions

2020-11-16 08:07 UTC, aschuler84 commented on src/extension.js
> +	let disposable = vscode.commands.registerCommand('fsh-editor.helloWorld', () => {
remove irrelevant/unused dummy code

2020-11-16 08:07 UTC, aschuler84 commented on src/extension.js
> +        vscode.window.showInformationMessage('Hello World from fsh_editor!')
not sure if this is still needed

2020-11-16 08:07 UTC, aschuler84 commented on src/parser/rules_parser/parse.js
> +}
Is logging to the console the desired way to handle parsing errors?

2020-11-16 08:07 UTC, aschuler84 commented on test/suite/index.js
> +};
Are there any tests?

2020-11-16 08:14 UTC, oliver-krauss commented on README.md
> +Different colorization for declaration keywords, additional keyword, comments, and todos.
Technically yes as colorization means to color in something that is usually b/w vs coloring meaning that something is presented in a color.

2020-11-16 08:17 UTC, oliver-krauss commented on extension.js
> +}
Yeah, I just commited the code I didn't write it, so I won't touch any of your code comments. Your choice if you merge or assign @SophieBauernfeind

2020-11-16 11:26 UTC, pointan commented on src/extension.js
> +//this definisions are for the language server
And I guess it should be `these` because definitions is plural.

2021-03-05 08:44 UTC, aschuler84 approved these changes

2021-03-11 06:41 UTC, merged